### ISSUE TITLE
Campaigns and queues Upload Audio File Issue

### ISSUE THREAD

**Issue by Khaled-IamZ** [magnussolution/magnusbilling#575]
when i create a campaigns the Audio file not upload and give me wait message  and can't create the campaign
i try to create it without audio file the campaign is created and when i try to upload the audio file i got the wait message and the campaign not saved
i tested the audio file and upload it as a IVR and working without any problem 
the same issue at queues can't upload audio file at periodic announce but audiomusiconhold working and upload the audio file
i Tested it on Centos 7 and Debian 10 using Magnusbilling 7

**Comment by magnussolution** [comment]
fixed

**Comment by Khaled-IamZ** [comment]
@magnussolution Not Fixed 
i have been installed MagnusBilling V 7.8.0.7 after your reply. and the above issue not resolved please find the below attached file including wait message  this message take more than an hour and didn't save the campaigns
FYI wav file size is 318KB and uploaded at ivr and magnuscallcenter4 without any issues
![Capture](https://user-images.githubusercontent.com/74547726/163468876-49d90043-1215-4c95-a7f4-5825cce6b7b2.JPG)
