### ISSUE TITLE
Inactive DID of users listed in agent DID view as well

### ISSUE THREAD

**Issue by uzair329** [magnussolution/magnusbilling#603]
**Describe the bug**
when we inactive any DID on our admin portal . That DID also listed in agent access as well he can see list of DID and its details they get skeptic and think they are charged for these DID's

**To Reproduce**
1. create and agent
2. Create any user and assigned DID to your user in admin portal
3. now open agent panel you will see no DID till than
4. now release that DID from user and inactive as well you will see that DID in agent panel now

**Comment by magnussolution** [comment]
fixed, just update

**Comment by uzair329** [comment]
i have checked its still appeared in agent panel . I have open agent ID on incognito mode
